package com.socket.msg
{
	public class MsgDef
	{
		public static var NM_BEGIN:int = 0;// 开始
		public static var NM_LOGIN:int = 1// 登录
		public static var NM_LOGIN_OK:int = 2// 登录成功
		public static var NM_LOGIN_FAIL:int = 3// 登录失败
		public static var NM_PLAYER_INFO:int = 4// 角色信息
		public static var NM_PLAYER_NEW:int = 5// 创建角色
		public static var NM_PLAYER_NEW_OK:int = 6// 创建角色成功
		public static var NM_PLAYER_NEW_FAIL:int = 7// 创建角色失败
		public static var NM_PLAYER_DEL:int = 8// 删除玩家
		public static var NM_PLAYER_DEL_OK:int = 9// 取得玩家状态
		public static var NM_PLAYER_DEL_FAIL:int = 10// 取得玩家状态
		public static var NM_PLAYER_GET:int = 11// 取得玩家状态
		public static var NM_PLAYER_GET_OK:int = 12// 取得玩家状态
		public static var NM_PLAYER_GET_FAIL:int = 13// 取得玩家状态
		public static var NM_PLAYER_MAIN:int = 14// 玩家数据
		public static var NM_PLAYER_DATA:int = 15// 玩家数据
		public static var NM_PLAYER_ITEM:int = 16// 玩家物品
		public static var NM_PLAYER_SKILL:int = 17// 玩家技能
		public static var NM_PLAYER_EFFECT:int = 18// 玩家状态
		public static var NM_PLAYER_TASK:int = 19// 玩家任务
		public static var NM_PLAYER_KILL:int = 20// 玩家杀怪
		public static var NM_PLAYER_DAY:int = 21// 玩家每日
		public static var NM_PLAYER_FRIEND:int = 22// 玩家好友
		public static var NM_PLAYER_ENEMY:int = 23// 玩家仇人
		public static var NM_PLAYER_WORD:int = 24// 玩家留言
		public static var NM_PLAYER_INI:int = 25// 附加消息
		public static var NM_FILE_NAME:int = 26// 文件传输
		public static var NM_FILE_DATA:int = 27// 文件传输
		public static var NM_NAME:int = 28// 角色名称
		public static var NM_COMMAND:int = 29// 命令
		public static var NM_GM_COMMAND:int = 30// GM命令
		public static var NM_SQL_COMMAND:int = 31// 数据库命令
		public static var NM_GAME_LOGIN:int = 32// 登录游戏角色
		public static var NM_GAME_STAT:int = 33// 游戏统计信息
		public static var NM_GET_PRESENT:int = 34// 取得充值赠品
		public static var NM_BUY_SHOP_ITEM:int = 35// 购买商城道具
		public static var NM_CHAT:int = 36// 频道聊天
		public static var NM_P2P_CHAT:int = 37// 私聊聊天
		public static var NM_SYS_CHAT:int = 38// 系统消息
		public static var NM_FRIEND_CHAT:int = 39// 单人小窗口聊天
		public static var NM_LINE_INFO:int = 40// 线信息
		public static var NM_SEND_BUY_ITEM:int = 41// 提供收购物品
		public static var NM_NPC_POS:int = 42// 位置
		public static var NM_NPC_STAND:int = 43// NPC 站立
		public static var NM_NPC_RUN:int = 44// NPC 行走
		public static var NM_NPC_ATTACK:int = 45// NPC 攻击
		public static var NM_NPC_MAGIC:int = 46// NPC 魔法
		public static var NM_NPC_DIE:int = 47// NPC 死亡
		public static var NM_NPC_LIFE:int = 48// NPC 生命
		public static var NM_NPC_EFFECT:int = 49// NPC 效果
		public static var NM_NPC_ATTACK_SPC:int = 50// NPC 攻击玩家
		public static var NM_NPC_ATTACK_PET:int = 51// NPC 攻击宠物
		public static var NM_NPC_STOP_ATTACK:int = 52// NPC 停止攻击
		public static var NM_NPC_DELETE:int = 53// NPC 消失
		public static var NM_SPC_STATE:int = 54// 玩家状态
		public static var NM_SPC_ENTER_MAP:int = 55// 进入地图
		public static var NM_SPC_LEAVE_MAP:int = 56// 离开地图
		public static var NM_PING:int = 57// PING
		public static var NM_SPC_POS:int = 58// 位置
		public static var NM_SPC_DIR:int = 59// 方向
		public static var NM_SPC_STAND:int = 60// 站立
		public static var NM_SPC_RUN:int = 61// 跑步
		public static var NM_SPC_JUMP:int = 62// 跳跃
		public static var NM_SPC_ATTACK:int = 63// 攻击
		public static var NM_SPC_MAGIC:int = 64// 魔法
		public static var NM_SPC_DIE:int = 65// 死亡
		public static var NM_SPC_SIT:int = 66// 打坐
		public static var NM_SPC_DIG:int = 67// 采矿
		public static var NM_SPC_GET:int = 68// 采集
		public static var NM_SPC_FRIEND:int = 69// 好友列表
		public static var NM_SPC_LIFE:int = 70// 玩家生命
		public static var NM_SPC_MANA:int = 71// 玩家法力
		public static var NM_SPC_GOLD:int = 72// 玩家金子
		public static var NM_SPC_SILVER:int = 73// 玩家银子
		public static var NM_SPC_PK:int = 74// 玩家PK
		public static var NM_SPC_ITEM:int = 75// 物品数据
		public static var NM_SPC_PROMOTE:int = 76// 飞升
		public static var NM_SPC_PARTY:int = 77// 暂时没用
		public static var NM_SPC_LEVEL:int = 78// 玩家等级
		public static var NM_SPC_EXP:int = 79// 玩家经验
		public static var NM_SPC_NUMEN:int = 80// 玩家元神
		public static var NM_SPC_EVIL:int = 81// 玩家邪恶
		public static var NM_SPC_FAME:int = 82// 玩家声望
		public static var NM_SPC_TEAM:int = 83// 组队信息
		public static var NM_SPC_BUY:int = 84// 玩家收购物品
		public static var NM_SPC_EFFECT:int = 85// 效果
		public static var NM_SPC_SKILLEFFECT:int = 86// 技能效果
		public static var NM_SPC_INFO:int = 87// 玩家信息
		public static var NM_SPC_FAVOR:int = 88// 情侣好感
		public static var NM_SPC_EQUIP:int = 89// 玩家装备
		public static var NM_SPC_MOUNT:int = 90// 玩家上下坐骑
		public static var NM_SPC_TITLE:int = 91// 玩家称号
		public static var NM_CHARGE:int = 92// 账号充值
		public static var NM_DEL_ITEM:int = 93// 删除物品
		public static var NM_NUM_ITEM:int = 94// 物品数量
		public static var NM_POS_ITEM:int = 95// 物品位置
		public static var NM_USE_ITEM:int = 96// 使用物品
		public static var NM_BUY_ITEM:int = 97// 买入物件
		public static var NM_SELL_ITEM:int = 98//卖出物品
		public static var NM_PICK_ITEM:int = 99// 拾起物品
		public static var NM_DROP_ITEM:int = 100// 放下物品
		public static var NM_QUICK_ITEM:int = 101// 快捷物品
		public static var NM_NEW_MAP_ITEM:int = 102// 新增地图物品
		public static var NM_DEL_MAP_ITEM:int = 103// 删除地图物品
		public static var NM_MAP_NPC:int = 104// 地图人物
		public static var NM_MAP_MPC:int = 105// 地图玩家
		public static var NM_USE_POINT:int = 106// 使用潜能点
		public static var NM_SEE_STATE:int = 107// 玩家状态
		public static var NM_SEE_EQUIP_ITEM:int = 108// 玩家物品
		public static var NM_SEE_TRADE_ITEM:int = 109// 交易物件
		public static var NM_SEND_BOX_ITEM:int = 110// 宝箱物品
		public static var NM_QUESTION:int = 111// 取得问题
		public static var NM_ANSWER:int = 112// 返回问题
		public static var NM_TOPTEN:int = 113// 取得排行榜
		public static var NM_TASK_LOG:int = 114// 任务记录
		public static var NM_FAMILY_INFO:int = 115// 家族信息
		public static var NM_FAMILY_MEMBER:int = 116// 家族成员
		public static var NM_FAMILY_BOARD:int = 117// 家族公告
		public static var NM_FACTION_INFO:int = 118// 帮派信息
		public static var NM_FACTION_MEMBER:int = 119// 帮派成员
		public static var NM_FACTION_BOARD:int = 120// 帮派公告
		public static var NM_PARTY_INFO:int = 121// 国家信息
		public static var NM_PARTY_MEMBER:int = 122// 国家成员
		public static var NM_PARTY_BOARD:int = 123// 国家公告
		public static var NM_TEAM_MEMBER:int = 124// 组队信息
		public static var NM_SALE_ITEM_COST:int = 125// 摆摊物品价格
		public static var NM_SALE_ITEM_AD:int = 126// 摆摊物品
		public static var NM_SALE_ITEM_START:int = 127// 摆摊物品
		public static var NM_SALE_ITEM_STOP:int = 128// 摆摊物品
		public static var NM_NEW_SALE_ITEM:int = 129// 摆摊物品
		public static var NM_DEL_SALE_ITEM:int = 130// 摆摊物品
		public static var NM_BUY_SALE_ITEM:int = 131// 摆摊物品
		public static var NM_SALE_WORD:int = 132// 摆摊留言
		public static var NM_RUN_TALK:int = 133// 运行客户端脚本
		public static var NM_RUN_TASK:int = 134// 运行服务器脚本
		public static var NM_PET_NEW:int = 135// 放宠物
		public static var NM_PET_DELETE:int = 136// 收宠物
		public static var NM_PET_STAND:int = 137// 站立
		public static var NM_PET_RUN:int = 138// 跑步
		public static var NM_PET_ATTACK:int = 139// 攻击
		public static var NM_PET_DIE:int = 140// 死亡
		public static var NM_PET_LIFE:int = 141// 宠物生命
		public static var NM_PET_LEVEL:int = 142// 宠物等级
		public static var NM_PET_EFFECT:int = 143// 宠物效果
		public static var NM_PET_EXP:int = 144// 宠物经验
		public static var NM_PET_POS:int = 145// 宠物位置
		public static var NM_RECV_MAIL:int = 146// 收到的邮件
		public static var NM_SEND_MAIL:int = 147// 发送的邮件
		public static var NM_TIP_TALK:int = 148//提示消息
		public static var NM_TIP_TASK:int = 149//提示消息
		public static var NM_GET_GOLD:int = 150//领取金子
		public static var NM_RECV_AUCTION:int = 151//客户端收到拍卖物品
		public static var NM_SEND_AUCTION:int = 152//客户端发送拍卖物品
		public static var NM_QUERY_AUCTION:int = 153//查询拍卖物品
		public static var NM_WORLD_CHAT:int = 154//世界聊天
		public static var NM_SQL_TOPTEN:int = 155//排行榜返回结果
		public static var NM_SQL_TOP1000:int = 156//排行榜返回结果
		public static var NM_SQL_FACTION:int = 157//帮会
		public static var NM_SQL_FAMILY:int = 158//家族
		public static var NM_SQL_QUESTION:int = 159//问题
		public static var NM_SQL_MAIL:int = 160//邮件
		public static var NM_SQL_AUCTION:int = 161//拍卖
		public static var NM_SQL_COMPENSATE:int = 162//补偿
		public static var NM_ITEM_WEAR:int = 163//物品耐久
		public static var NM_GAME_LOGOUT:int = 164// 登出游戏
		public static var NM_SWITCH_SERVER:int = 165//转换所在服务器
		public static var NM_FILE_INFO:int = 166//文件信息
		public static var NM_PASSWORD:int = 167//修改密码
		public static var NM_SQL_FAMILY_MEMBER:int = 168//家族成员
		public static var NM_SQL_FAMILY_BOARD:int = 169//家族公告
		public static var NM_SQL_FACTION_MEMBER:int = 170//帮会成员
		public static var NM_SQL_FACTION_BOARD:int = 171//帮会公告
		public static var NM_SYS_TASK:int = 172//系统任务
		public static var NM_QUERY_TRADE:int = 173//查询交易记录
		public static var NM_SQL_TRADE:int = 174//交易记录
		public static var NM_REG:int = 175//注册账号
		public static var NM_REG_OK:int = 176//注册成功
		public static var NM_REG_FAIL:int = 177//注册失败
		public static var NM_END:int = 178// 结束
		
		public function MsgDef()
		{
		}
	}
}